package mimetypes

import (
	"mime"
	"strings"
)

func AddExtensionType(contentType string, extensions string) {
	for _, ext := range strings.Split(extensions, " ") {
		mime.AddExtensionType("."+ext, contentType)
	}
}

func InitAdditionalMimeTypes() {
	AddExtensionType("text/markdown", "md")
	AddExtensionType("audio/ogg", "ogg oga")
	AddExtensionType("video/ogg", "ogv")
	AddExtensionType("application/ogg", "ogx")
	AddExtensionType("video/webm", "webm")
	AddExtensionType("audio/webm", "webma")
	AddExtensionType("application/javascript", "js")
	AddExtensionType("application/typescript", "ts")
	AddExtensionType("application/json", "json")
	AddExtensionType("application/vnd.msoutlook", "msg")
	AddExtensionType("message/rfc822", "eml")
	AddExtensionType("text/plain", "txt text")
	AddExtensionType("image/tiff", "tif tiff")
	AddExtensionType("application/octet-stream", "a")
	AddExtensionType("text/vnd.abc", "abc")
	AddExtensionType("text/html", "acgi")
	AddExtensionType("video/animaflex", "afl")
	AddExtensionType("application/postscript", "ai")
	AddExtensionType("audio/aiff", "aif aifc aiff")
	AddExtensionType("application/mime", "aps")
	AddExtensionType("application/octet-stream", "arc")
	AddExtensionType("application/arj", "arj")
	AddExtensionType("application/octet-stream", "arj")
	AddExtensionType("text/asp", "asp")
	AddExtensionType("audio/basic", "au")
	AddExtensionType("video/avi", "avi")
	AddExtensionType("video/msvideo", "avi")
	AddExtensionType("video/avs-video", "avs")
	AddExtensionType("application/mac-binary", "bin")
	AddExtensionType("application/macbinary", "bin")
	AddExtensionType("application/octet-stream", "bin")
	AddExtensionType("image/bmp", "bm bmp")
	AddExtensionType("application/book", "boo book")
	AddExtensionType("text/plain", "c")
	AddExtensionType("text/plain", "c++")
	AddExtensionType("application/vnd.ms-pki.seccat", "cat")
	AddExtensionType("text/plain", "cc")
	AddExtensionType("application/clariscad", "ccad")
	AddExtensionType("application/cdf", "cdf")
	AddExtensionType("application/pkix-cert", "cer")
	AddExtensionType("application/java", "class")
	AddExtensionType("application/java-byte-code", "class")
	AddExtensionType("application/octet-stream", "com")
	AddExtensionType("text/plain", "com conf")
	AddExtensionType("application/mac-compactpro", "cpt")
	AddExtensionType("application/pkcs-crl", "crl")
	AddExtensionType("application/pkix-crl", "crl")
	AddExtensionType("application/pkix-cert", "crt")
	AddExtensionType("text/css", "css")
	AddExtensionType("text/plain", "cxx")
	AddExtensionType("text/plain", "def")
	AddExtensionType("video/dl", "dl")
	AddExtensionType("application/msword", "doc dot")
	AddExtensionType("application/vnd.openxmlformats-officedocument.wordprocessingml.document", "docx")
	AddExtensionType("application/commonground", "intex.dp")
	AddExtensionType("application/drafting", "drw")
	AddExtensionType("application/octet-stream", "dump")
	AddExtensionType("model/vnd.dwf", "dwf")
	AddExtensionType("application/acad", "dwg")
	AddExtensionType("image/vnd.dwg", "dwg")
	AddExtensionType("application/dxf", "dxf")
	AddExtensionType("image/vnd.dwg", "dxf")
	AddExtensionType("application/postscript", "eps")
	AddExtensionType("application/envoy", "evy")
	AddExtensionType("application/octet-stream", "exe")
	AddExtensionType("text/plain", "f f77 f90")
	AddExtensionType("application/vnd.fdf", "fdf")
	AddExtensionType("application/fractals", "fif")
	AddExtensionType("image/fif", "fif fli")
	AddExtensionType("image/florian", "flo")
	AddExtensionType("text/vnd.fmi.flexstor", "flx")
	AddExtensionType("text/plain", "for")
	AddExtensionType("image/vnd.fpx", "fpx")
	AddExtensionType("image/vnd.net-fpx", "fpx")
	AddExtensionType("application/freeloader", "frl")
	AddExtensionType("audio/make", "funk")
	AddExtensionType("text/plain", "g")
	AddExtensionType("image/g3fax", "g3")
	AddExtensionType("image/gif", "gif")
	AddExtensionType("video/gl", "gl")
	AddExtensionType("text/plain", "h")
	AddExtensionType("application/vnd.hp-hpgl", "hgl")
	AddExtensionType("text/plain", "hh")
	AddExtensionType("application/hlp", "hlp")
	AddExtensionType("application/vnd.hp-hpgl", "hpg")
	AddExtensionType("application/vnd.hp-hpgl", "hpgl")
	AddExtensionType("application/binhex", "hqx")
	AddExtensionType("application/binhex4", "hqx")
	AddExtensionType("application/mac-binhex", "hqx")
	AddExtensionType("application/mac-binhex40", "hqx")
	AddExtensionType("application/hta", "hta")
	AddExtensionType("text/html", "htm html htmls")
	AddExtensionType("text/webviewhtml", "htt")
	AddExtensionType("text/html", "htx")
	AddExtensionType("text/plain", "idc")
	AddExtensionType("image/ief", "ief")
	AddExtensionType("image/ief", "iefs")
	AddExtensionType("application/iges", "iges")
	AddExtensionType("model/iges", "iges")
	AddExtensionType("application/iges", "igs")
	AddExtensionType("model/iges", "igs")
	AddExtensionType("application/inf", "inf")
	AddExtensionType("audio/it", "it")
	AddExtensionType("i-world/i-vrml", "ivr")
	AddExtensionType("text/plain", "jav")
	AddExtensionType("text/plain", "java")
	AddExtensionType("image/jpeg", "jfif jfif-tbnl jpe jpeg jpg")
	AddExtensionType("image/jutvision", "jut")
	AddExtensionType("audio/midi", "kar")
	AddExtensionType("audio/nspaudio", "la")
	AddExtensionType("application/lha", "lha")
	AddExtensionType("application/octet-stream", "lha")
	AddExtensionType("application/octet-stream", "lhx")
	AddExtensionType("text/plain", "list")
	AddExtensionType("audio/nspaudio", "lma")
	AddExtensionType("text/plain", "log")
	AddExtensionType("text/plain", "lst")
	AddExtensionType("application/octet-stream", "lzh")
	AddExtensionType("application/lzx", "lzx")
	AddExtensionType("application/octet-stream", "lzx")
	AddExtensionType("text/plain", "m")
	AddExtensionType("video/mpeg", "m1v")
	AddExtensionType("audio/mpeg", "m2a")
	AddExtensionType("video/mpeg", "m2v")
	AddExtensionType("text/plain", "mar")
	AddExtensionType("application/mbedlet", "mbd")
	AddExtensionType("application/mcad", "mcd")
	AddExtensionType("image/vasa", "mcf")
	AddExtensionType("text/mcf", "mcf")
	AddExtensionType("application/netmc", "mcp")
	AddExtensionType("message/rfc822", "mht mhtml")
	AddExtensionType("audio/midi", "mid")
	AddExtensionType("music/crescendo", "mid")
	AddExtensionType("audio/midi", "midi")
	AddExtensionType("music/crescendo", "midi")
	AddExtensionType("message/rfc822", "mime")
	AddExtensionType("www/mime", "mime")
	AddExtensionType("application/base64", "mm")
	AddExtensionType("application/base64", "mme")
	AddExtensionType("audio/mod", "mod")
	AddExtensionType("video/quicktime", "moov")
	AddExtensionType("video/quicktime", "mov")
	AddExtensionType("audio/mpeg", "mp2 mp3 mpa mpga")
	AddExtensionType("video/mpeg", "mpe mpeg mpg")
	AddExtensionType("video/mp4", "mp4")
	AddExtensionType("application/vnd.ms-project", "mpp")
	AddExtensionType("application/marc", "mrc")
	AddExtensionType("audio/make", "my")
	AddExtensionType("image/naplps", "nap")
	AddExtensionType("image/naplps", "naplps")
	AddExtensionType("application/vnd.nokia.configuration-message", "ncm")
	AddExtensionType("application/octet-stream", "o")
	AddExtensionType("application/oda", "oda")
	AddExtensionType("application/pkcs10", "p10")
	AddExtensionType("application/pkcs-12", "p12")
	AddExtensionType("application/pkcs7-mime", "p7c")
	AddExtensionType("application/pkcs7-mime", "p7m")
	AddExtensionType("application/pkcs7-signature", "p7s")
	AddExtensionType("application/pro_eng", "part")
	AddExtensionType("text/pascal", "pas")
	AddExtensionType("application/vnd.hp-pcl", "pcl")
	AddExtensionType("application/pdf", "pdf")
	AddExtensionType("audio/make", "pfunk")
	AddExtensionType("audio/make.my.funk", "pfunk")
	AddExtensionType("image/pict", "pic")
	AddExtensionType("image/pict", "pict")
	AddExtensionType("application/vnd.ms-pki.pko", "pko")
	AddExtensionType("text/plain", "pl")
	AddExtensionType("image/png", "png")
	AddExtensionType("application/mspowerpoint", "pot")
	AddExtensionType("application/vnd.ms-powerpoint", "pot")
	AddExtensionType("application/vnd.ms-powerpoint", "ppa")
	AddExtensionType("application/mspowerpoint", "pps")
	AddExtensionType("application/vnd.ms-powerpoint", "pps")
	AddExtensionType("application/mspowerpoint", "ppt pptx")
	AddExtensionType("application/powerpoint", "ppt pptx")
	AddExtensionType("application/vnd.ms-powerpoint", "ppt pptx")
	AddExtensionType("application/mspowerpoint", "ppz")
	AddExtensionType("application/pro_eng", "prt")
	AddExtensionType("application/postscript", "ps")
	AddExtensionType("application/octet-stream", "psd")
	AddExtensionType("application/vnd.ms-powerpoint", "pwz")
	AddExtensionType("audio/vnd.qcelp", "qcp")
	AddExtensionType("video/quicktime", "qt")
	AddExtensionType("image/cmu-raster", "ras")
	AddExtensionType("image/cmu-raster", "rast")
	AddExtensionType("image/vnd.rn-realflash", "rf")
	AddExtensionType("application/vnd.rn-realmedia", "rm")
	AddExtensionType("audio/mid", "rmi")
	AddExtensionType("application/ringing-tones", "rng")
	AddExtensionType("application/vnd.nokia.ringing-tone", "rng")
	AddExtensionType("application/vnd.rn-realplayer", "rnx")
	AddExtensionType("image/vnd.rn-realpix", "rp")
	AddExtensionType("text/richtext", "rt")
	AddExtensionType("text/vnd.rn-realtext", "rt")
	AddExtensionType("application/rtf", "rtf")
	AddExtensionType("text/richtext", "rtf")
	AddExtensionType("application/rtf", "rtx")
	AddExtensionType("text/richtext", "rtx")
	AddExtensionType("video/vnd.rn-realvideo", "rv")
	AddExtensionType("audio/s3m", "s3m")
	AddExtensionType("application/octet-stream", "saveme")
	AddExtensionType("text/plain", "sdml")
	AddExtensionType("application/sdp", "sdp")
	AddExtensionType("application/sounder", "sdr")
	AddExtensionType("application/sea", "sea")
	AddExtensionType("application/set", "set")
	AddExtensionType("text/sgml", "sgm")
	AddExtensionType("text/sgml", "sgml")
	AddExtensionType("text/html", "shtml")
	AddExtensionType("application/smil", "smi")
	AddExtensionType("application/smil", "smil")
	AddExtensionType("audio/basic", "snd")
	AddExtensionType("application/solids", "sol")
	AddExtensionType("application/futuresplash", "spl")
	AddExtensionType("application/streamingmedia", "ssm")
	AddExtensionType("application/vnd.ms-pki.certstore", "sst")
	AddExtensionType("application/step", "step")
	AddExtensionType("application/sla", "stl")
	AddExtensionType("application/vnd.ms-pki.stl", "stl")
	AddExtensionType("application/step", "stp")
	AddExtensionType("image/vnd.dwg", "svf")
	AddExtensionType("application/toolbook", "tbk")
	AddExtensionType("application/plain", "text")
	AddExtensionType("text/plain", "text")
	AddExtensionType("application/gnutar", "tgz")
	AddExtensionType("audio/tsp-audio", "tsi")
	AddExtensionType("application/dsptype", "tsp")
	AddExtensionType("audio/tsplayer", "tsp")
	AddExtensionType("text/tab-separated-values", "tsv")
	AddExtensionType("image/florian", "turbot")
	AddExtensionType("text/plain", "txt")
	AddExtensionType("text/uri-list", "uni")
	AddExtensionType("text/uri-list", "unis")
	AddExtensionType("application/i-deas", "unv")
	AddExtensionType("text/uri-list", "uri")
	AddExtensionType("text/uri-list", "uris")
	AddExtensionType("application/octet-stream", "uu")
	AddExtensionType("application/vda", "vda")
	AddExtensionType("video/vdo", "vdo")
	AddExtensionType("application/groupwise", "vew")
	AddExtensionType("video/vivo", "viv")
	AddExtensionType("video/vnd.vivo", "viv")
	AddExtensionType("video/vivo", "vivo")
	AddExtensionType("video/vnd.vivo", "vivo")
	AddExtensionType("application/vocaltec-media-desc", "vmd")
	AddExtensionType("application/vocaltec-media-file", "vmf")
	AddExtensionType("audio/voc", "voc")
	AddExtensionType("video/vosaic", "vos")
	AddExtensionType("audio/voxware", "vox")
	AddExtensionType("model/vrml", "vrml")
	AddExtensionType("application/wordperfect6.0", "w60")
	AddExtensionType("application/wordperfect6.1", "w61")
	AddExtensionType("application/msword", "w6w")
	AddExtensionType("audio/wav", "wav")
	AddExtensionType("image/vnd.wap.wbmp", "wbmp")
	AddExtensionType("application/vnd.xara", "web")
	AddExtensionType("application/msword", "wiz")
	AddExtensionType("windows/metafile", "wmf")
	AddExtensionType("text/vnd.wap.wml", "wml")
	AddExtensionType("application/vnd.wap.wmlc", "wmlc")
	AddExtensionType("text/vnd.wap.wmlscript", "wmls")
	AddExtensionType("application/vnd.wap.wmlscriptc", "wmlsc")
	AddExtensionType("application/msword", "word")
	AddExtensionType("application/wordperfect", "wp")
	AddExtensionType("application/wordperfect", "wp5")
	AddExtensionType("application/wordperfect6.0", "wp5")
	AddExtensionType("application/wordperfect", "wp6")
	AddExtensionType("application/wordperfect", "wpd")
	AddExtensionType("application/mswrite", "wri")
	AddExtensionType("model/vrml", "wrl")
	AddExtensionType("model/vrml", "wrz")
	AddExtensionType("text/scriplet", "wsc")
	AddExtensionType("image/xbm", "xbm")
	AddExtensionType("xgl/drawing", "xgz")
	AddExtensionType("image/vnd.xiff", "xif")
	AddExtensionType("application/excel", "xl")
	AddExtensionType("application/excel", "xla")
	AddExtensionType("application/excel", "xlb")
	AddExtensionType("application/vnd.ms-excel", "xlb")
	AddExtensionType("application/excel", "xlc")
	AddExtensionType("application/vnd.ms-excel", "xlc")
	AddExtensionType("application/excel", "xld")
	AddExtensionType("application/excel", "xlk")
	AddExtensionType("application/excel", "xll")
	AddExtensionType("application/vnd.ms-excel", "xll")
	AddExtensionType("application/excel", "xlm")
	AddExtensionType("application/vnd.ms-excel", "xlm")
	AddExtensionType("application/excel", "xlsx xls")
	AddExtensionType("application/vnd.ms-excel", "xlsx xls")
	AddExtensionType("application/excel", "xlt")
	AddExtensionType("application/excel", "xlv")
	AddExtensionType("application/excel", "xlw")
	AddExtensionType("application/vnd.ms-excel", "xlw")
	AddExtensionType("audio/xm", "xm")
	AddExtensionType("application/xml", "xml")
	AddExtensionType("text/xml", "xml")
	AddExtensionType("xgl/movie", "xmz")
	AddExtensionType("image/xpm", "xpm")
	AddExtensionType("application/zip", "zip")
	AddExtensionType("application/octet-stream", "zoo")
}
